//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipmleCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string EmployeeID { get; set; }
        public string Name { get; set; }
        public string Father_Name { get; set; }
        public string Mother_Name { get; set; }
        public string NID { get; set; }
        public string Present_Address { get; set; }
        public string Permanent_Address { get; set; }
        public Nullable<System.DateTime> Join_Date { get; set; }
        public string Designation { get; set; }
        public Nullable<int> Basic { get; set; }
        public string Bank_A_C_No { get; set; }
    }
}
